### PR TITLE
fix: handle unknown topic etc.

### LINKED ISSUE #702: Close Error Result Channel if No Topic Matches Message
If we get a message from a topic that we have not configured we will push an error channel into the results channel that will never have a message pushed into it. This will halt processing. We need to close the error channel in addition to logging the message about the bad topic/message mapping.

https://github.com/brave-intl/challenge-bypass-server/blob/17fec6895e373d00b87317650c70bfda128784a9/kafka/main.go#L200

### LINKED ISSUE #703: Make Error Result Channel Have a Buffer of 1
As configured, the error channel will exist until a recipient reads the channel. Instead, allow exactly one result to be buffered. This will allow cleanup of resources related to processing in the event that the reader of the error channel is delayed in receiving.

https://github.com/brave-intl/challenge-bypass-server/blob/17fec6895e373d00b87317650c70bfda128784a9/kafka/main.go#L173

### LINKED ISSUE #704: Configure Result Channel to Have a CPU-Bound Buffer Size
Because we are doing CPU-intensive work, it is unlikely that 100 is the most efficient buffer size here. Instead, use `runtime.NumCPU() + something` to more intelligently set this buffer limit.

https://github.com/brave-intl/challenge-bypass-server/blob/17fec6895e373d00b87317650c70bfda128784a9/kafka/main.go#L92

### PR DESCRIPTION
**Pull request by ibukanov**
Refactor processMessagesIntoBatchPipeline to ensure that it closes the message channel to signal that the message processing is ready including the case when the message topic does not match any of configured topics. For that move all processing of the message including the search for topic processors to runMessageProcessor() groutine and use defer to close the channel. That required to change the message channel to be of struct{} type and store the error in the message itself so a simple defer close(msg.done) can be used to cover both normal and error cases.

Provide unit tests for processMessagesIntoBatchPipeline that cover success and error paths.

Bound batchPipeline capacity by the number of CPU cores to avoid running too many CPU-intensive tasks in parallel.

Closes #702
Closes #703
Closes #704

### CODE REVIEW

File: kafka/main.go [hunk 1]
```diff
@@ -19,34 +20,27 @@ import (
...
-	Topic          string
-	ResultProducer *kafka.Writer
-	Processor      Processor
-	Group          string
+	Topic     string
+	Processor Processor
 }
 
 // MessageContext is used for channel coordination when processing batches of messages
 type MessageContext struct {
```
Comment (Sneagan) [inline kafka/main.go:39]: Good simplification here.

**Review by Sneagan — APPROVED** [review]
