### PR TITLE
fix: return correct signing key for FetchAllIssuers

### LINKED ISSUE #479: `GET v1/issuer` relies on database insert order to return the correct public key
The `GET v1/issuer` endpoint is critical to the correct behaviour of ads, as the data returned in this endpoint is used to inform browsers of the public keys which are the current set of valid issuers. An incorrect list here will cause browsers to reject all tokens, and, after they have used up their pool for stored tokens, prevent display of ads.

In the code that generates this response, the logic returns the _last_ public key in the list returned by `FetchAllIssuers`:

https://github.com/brave-intl/challenge-bypass-server/blob/1a4af4ea1d0c564b5151ac3ee7eb11e98d97b140/server/issuers.go#L234-L238

I had to read this code a few times: `publicKey` gets overwritten each time round the loop, so what this actually does is return the last one in the list.

That list of public keys for each issuer is generated with this select statement:

https://github.com/brave-intl/challenge-bypass-server/blob/1a4af4ea1d0c564b5151ac3ee7eb11e98d97b140/server/db.go#L567-L579

which returns the one with the greatest `end_at` date last. So this looks correct.

*except* `end_at` and `start_at` are nullable columns, and in production ads both columns are null for all keys.

So in fact, by accident of what postgres does in this particular case when there is no `order by` that applies and it chose to do a full table scan to answer the query, you end up with the most recently inserted. However this is very likely to cause issues in the future.

This should return the key using exactly the same logic that cbp uses to select the key when signing the message. That follows a completely different code path - these should use the same code path.

### PR DESCRIPTION
**Pull request by IanKrieger**
Closes #479

### CODE REVIEW

File: server/issuers.go [hunk 1]
```diff
@@ -224,22 +225,27 @@ func (c *Server) issuerGetAllHandler(w http.ResponseWriter, r *http.Request) *ha
...
+	for _, value := range marshalledIssuers {
+		iss := value.Issuer
+		issuerKeySigningKey := value.SigningKey
+		respIssuers = append(respIssuers, issuerResponse{
+			iss.ID.String(),
+			iss.IssuerType,
+			issuerKeySigningKey.PublicKey(),
+			iss.ExpiresAt.Format(time.RFC3339),
+			iss.IssuerCohort,
+		})
```
Comment (IanKrieger) [inline server/issuers.go:245]: So with `utils.MarshalIssuersAndSigningKeys` we get a map of the issuer and it's various issuerKeys.

It seems to me that we can just return the issuer as well as it's actual signing key, not just the last one as it was previously. 

I do wonder though, if we should exclude anything that has "expired" (seems like yes).

File: server/db.go [hunk 2]
```diff
@@ -415,192 +335,111 @@ func (c *Server) fetchIssuerByType(ctx context.Context, issuerType string) (*Iss
...
-			FROM v3_issuer_keys where issuer_id=$1 and
-			(
-				(select version from v3_issuers where issuer_id=$1)<=2
-				or end_at > now()
-			)
-			ORDER BY end_at ASC NULLS FIRST, start_at ASC`,
-			convertedIssuer.ID,
+			FROM v3_issuer_keys 
+			WHERE issuer_id=$1
+			  AND ($2 OR (end_at > now() OR end_at is null))
```
Comment (IanKrieger) [inline server/db.go:418]: After a lot of messing around with this, it appears that there are some tests that fully depend on `version <=2 OR end at is in the future` so basically this statement becomes:
```
SELECT * from v3_issuer_keys where issuer_id = 'id' AND true;
```

I have now changed the SQL to properly order the data, wondering if it should be left there, or more should be done

**Review by Sneagan — APPROVED** [review]
